<a href="https://colab.research.google.com/github/kartikpunjabi111/PCA/blob/master/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import numpy as np
import pandas as pd  

In [0]:
dataset=np.loadtxt(open('/content/drive/My Drive/PCA_dataset'), delimiter='\t')
print( dataset.shape)
print(dataset[:2])
#take data set  /content/Untitled Document


(1826, 4)
[[ 0.065 -0.027 -0.11  -0.046]
 [ 0.063  0.063  0.024 -0.044]]


In [0]:
a,b=dataset.shape

In [0]:
#pre-processing : Mean normalization  #PCA algorithm 
mu=np.zeros(b)
npdataset=np.array(dataset)
for j in range (0,b):
  for i in range (0,a):
    mu[j]+=dataset[i][j]
mu=mu/a
print(mu)
for j in range (0,b):
  for i in range (0,a):
    dataset[i][j]=dataset[i][j]-mu[j]
print(dataset)



[-0.00301424 -0.00043812  0.00115772 -0.00344633]
[[ 0.06801424 -0.02656188 -0.11115772 -0.04255367]
 [ 0.06601424  0.06343812  0.02284228 -0.04055367]
 [-0.02098576 -0.05056188 -0.01315772  0.03244633]
 ...
 [-0.04598576  0.06343812 -0.18915772  0.04544633]
 [-0.00898576  0.12043812  0.10884228 -0.04055367]
 [ 0.09301424  0.03943812  0.17184228  0.00544633]]


## Reducing the dimension from  **4 to K dimension**

In [0]:
no_of_dim=4  # Value of K(To number of dimenisions we want to reduce)

In [0]:
#computing the covariance matrix
cov=dataset[i]

In [0]:
tempmatarr=np.zeros((a,4,4))

In [0]:
for i in range (0,a):
  cov=np.matmul((np.asmatrix(dataset[i]).transpose()),np.asmatrix(dataset[i]))
  tempmatarr[i]=cov

In [0]:
from scipy.linalg import svd
Z=np.zeros((a,4,no_of_dim))

In [0]:
for i in range (0,a):
  U, s, VT = svd(tempmatarr[i])
  Z[i]=U[:,:no_of_dim]
print(Z[1])

[[-0.64274588  0.75056396  0.11647195 -0.09982865]
 [-0.61766353 -0.38960225 -0.48905677  0.47699615]
 [-0.22240323 -0.24888386 -0.36749909 -0.86806569]
 [ 0.39484972  0.47214473 -0.7824335   0.09471465]]


Taking first k columns of U matrices for reducing the dimension to 2

In [0]:
NewDataset=np.zeros((a,no_of_dim,1))
for i in range (0,a): 
  NewDataset[i]=Z[i].transpose()*(np.asmatrix(dataset[i]).transpose())
print(NewDataset.shape)

(1826, 4, 1)


**NewDataset** is with `desired number` of dimension