<a href="https://colab.research.google.com/github/kartikpunjabi111/PCA/blob/master/Try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
  !pip install pulp     
  #set path

     |████████████████████████████████| 39.2MB 102kB/s 


In [0]:
import numpy as np
import pandas as pd
  

Essence to omit training on million sized data and to visualize data

In [0]:
dataset=np.loadtxt(open('/content/Untitled Document'), delimiter='\t')
print( dataset.shape)
print(dataset[:2])
#take data set


(107, 4)
[[-0.049 -0.071 -0.132 -0.01 ]
 [-0.042 -0.073 -0.007 -0.105]]


In [0]:
a,b=dataset.shape
print(a,b)
#PCA algorithm


107 4


In [0]:
#pre-processing : Mean normalization 
mu=np.zeros(a)
print(mu)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
npdataset=np.array(dataset)

In [0]:
for i in range (0,a):
  for j in range (0,b):
    mu[i]+=dataset[i][j]

mu=mu/4
print(mu)

[-0.0655  -0.05675  0.0055   0.01675  0.021   -0.073   -0.04525  0.0335
 -0.0175   0.03425 -0.0025  -0.02975 -0.05675  0.00025  0.06775  0.03125
 -0.04875 -0.06275  0.00125  0.04075 -0.008   -0.0585   0.0105   0.0085
 -0.07375  0.0185   0.06175  0.02025  0.027   -0.00175  0.03475 -0.00125
 -0.0745  -0.05125  0.008    0.063    0.006   -0.07575 -0.0325   0.01275
 -0.04025 -0.06475  0.0305  -0.01825 -0.07525 -0.05425 -0.02575 -0.0545
 -0.0555  -0.03375 -0.0255  -0.034   -0.0425  -0.005    0.07325  0.016
  0.0305   0.02    -0.01425 -0.00275  0.014    0.0195   0.0255   0.01225
 -0.0005  -0.04525 -0.04875 -0.03625 -0.00375 -0.02075 -0.01575 -0.01725
 -0.0475  -0.0195  -0.006   -0.008   -0.00575  0.019    0.006   -0.04525
 -0.05675 -0.0525   0.01825  0.0335  -0.0175  -0.08425 -0.0535  -0.02075
  0.035   -0.005   -0.0085  -0.04725 -0.02225  0.025    0.04025  0.014
 -0.0515   0.08475  0.0025   0.07875  0.02625 -0.02325 -0.0085  -0.00075
 -0.07825 -0.07375 -0.00475]


## Reducing the dimension fromm  **4 to k**

In [0]:
#computing the covariance matrix
cov=dataset[i]

In [0]:
tempmatarr=np.zeros((a,4,4))

In [0]:
for i in range (0,a):
  cov=np.matmul((np.asmatrix(dataset[i]).transpose()),np.asmatrix(dataset[i]))
  tempmatarr[i]=cov

In [0]:
from scipy.linalg import svd

In [0]:
U, s, VT = svd(tempmatarr[1])
print(U)

[[-0.20289895 -0.9789739   0.01514094 -0.01459029]
 [ 0.22353274 -0.06141385 -0.97275593  0.00271129]
 [-0.68435408  0.1288943  -0.16344981  0.69880606]
 [ 0.66372029 -0.14568702  0.16370953  0.71515723]]


In [0]:
Taking first 2 coloumns of U matrices for reducing the dimension to two

NameError: ignored